#!/bin/sh /etc/rc.common
# Guest Guard init script to handle validate guest sessions

USE_PROCD=1
START=99
CAPTIVE_PATH=$(readlink -f $(dirname $(readlink -f "${initscript}"))/../..)
GUARD_BIN="${CAPTIVE_PATH}/bin/guard.lua"
RESTORE_BIN="${CAPTIVE_PATH}/bin/restore.lua"
LIST_BIN="${CAPTIVE_PATH}/bin/list.lua"
TKND_BIN="${CAPTIVE_PATH}/bin/tknd.lua"
MKCRON_BIN="${CAPTIVE_PATH}/bin/onboot.sh"
MKTOKEN_BIN="${CAPTIVE_PATH}/bin/mktoken.lua"

EXTRA_COMMANDS="token guard restore list"
EXTRA_HELP="	token	Generate token
	guard	Run session validation
	restore	Restore session firewall rules
	list 	List active sessions"

restore() {
    $RESTORE_BIN 2>&1 | logger -t captive[$$] -p daemon.info
}

boot() {
    $MKCRON_BIN 2>&1 | logger -t captive[$$] -p daemon.info
    restore
    start "$@"
}

token() {
	$MKTOKEN_BIN 2>&1
}

guard() {
	$GUARD_BIN 2>&1 | logger -t guard[$$] -p daemon.info
}

list() {
	$LIST_BIN 2>&1
}

start_service() {
	if [ -e /dev/ttyUSB0 ]; then
		procd_open_instance tknd
		procd_set_param command $TKND_BIN
		procd_set_param respawn 300 10 5
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	else
		logger -t tknd[$$] -p daemon.error "Token device not found, ignoring."
	fi
}