#!/bin/sh /etc/rc.common
# Guest Guard init script to handle validate guest sessions

USE_PROCD=1
START=99
CAPTIVE_PATH=$(readlink -f $(dirname $(readlink -f "${initscript}"))/../..)
GUARD_BIN="${CAPTIVE_PATH}/bin/guard.lua"
TKND_BIN="${CAPTIVE_PATH}/bin/tknd.lua"
ONBOOT_BIN="${CAPTIVE_PATH}/bin/onboot.sh"
TOKEN_BIN="${CAPTIVE_PATH}/bin/mktoken.lua"
EXTRA_COMMANDS="token guard"

boot() {
    $ONBOOT_BIN 2>&1 | logger -t captive[$$] -p daemon.info
}

token() {
	$TOKEN_BIN
}

guard() {
	$GUARD_BIN 2>&1 | logger -t guard[$$] -p daemon.info
}

start_service() {
	if [ -e /dev/ttyUSB0 ]; then
		procd_open_instance tknd
		procd_set_param command $TKND_BIN
		procd_set_param respawn 300 10 5
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi
}