#!/bin/sh /etc/rc.common
# Guest Guard init script to handle validate guest sessions

USE_PROCD=1
START=99
GGUARD_BIN=/mnt/sda1/auth.wro.tuxlan.es/bin/guard.lua

start_service() {
	procd_open_instance tknd
	procd_set_param command $GGUARD_BIN
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
    rc_procd start_service "$@"
    return 0
}

stop_service() {
    return 0
}

boot() {
    /mnt/sda1/auth.wro.tuxlan.es/devops/cron_check.sh
}