#!/bin/sh /etc/rc.common
# TKND init script to handle token device automatically

USE_PROCD=1
START=99
TKND_BIN=/mnt/sda1/auth.wro.tuxlan.es/bin/tknd.lua

start_service() {
	procd_open_instance tknd
	procd_set_param command $TKND_BIN
	procd_set_param respawn 300 10 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}